services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Softspring\CmsTranslationPlugin\Admin\Menu\ContentMenuProvider:
        tags: [ 'sfs_cms.admin_menu.content_menu_provider' ]

    Softspring\CmsTranslationPlugin\Admin\Routing\AdminRoutingProvider:
        tags: [ 'sfs_cms.admin_routing_provider' ]

    Softspring\CmsTranslationPlugin\Translator\TranslatorExtractor: ~

    Softspring\CmsTranslationPlugin\Exchange\Xliff12Exchanger:
        tags: [ 'sfs_cms.translation_plugin.exchanger' ]

    Softspring\CmsTranslationPlugin\Exchange\Exchanger:
        arguments: [!tagged_iterator { tag: 'sfs_cms.translation_plugin.exchanger', default_index_method: 'format' }]
