security:
    role_hierarchy:
        ROLE_SFS_CMS_ADMIN_CONTENTS_TRANSLATOR:
            - PERMISSION_SFS_CMS_ADMIN_CONTENT_TRANSLATIONS
            - PERMISSION_SFS_CMS_ADMIN_CONTENT_TRANSLATIONS_EXPORT
            - PERMISSION_SFS_CMS_ADMIN_CONTENT_TRANSLATIONS_IMPORT
        ROLE_SFS_CMS_ADMIN_SECTIONS_TRANSLATOR:
            - PERMISSION_SFS_CMS_ADMIN_SECTION_TRANSLATIONS
            - PERMISSION_SFS_CMS_ADMIN_SECTION_TRANSLATIONS_EXPORT
            - PERMISSION_SFS_CMS_ADMIN_SECTION_TRANSLATIONS_IMPORT